# Generated by Django 4.2.7 on 2025-02-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salesdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetail',
            name='sales_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salesmaster'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
