# Generated by Django 4.2.7 on 2025-02-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchasedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchasemaster'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
