# Generated by Django 4.2.7 on 2025-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_purchasedetails_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
