# Generated by Django 4.2.7 on 2025-02-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itemmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='brand_id',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.brandmaster'),
        ),
    ]
