# Generated by Django 4.2.7 on 2025-02-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemmaster_brand_alter_itemmaster_datetime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemMaster',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='core_item',
        ),
    ]
