# Generated by Django 4.2.7 on 2025-02-28 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_itemmaster_item_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
