# Generated by Django 4.2.7 on 2025-02-28 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_salesmaster_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
